# Initiative Template
name: "⭐️ New High-level Goal"
description: Create a new high-level goal that will contain multiple epics.
title: "⭐️ `[High-level Goal]` "
body:
  - type: textarea
    id: vision
    attributes:
      label: "Vision Statement"
      placeholder: "What is the overall vision for this high-level goal?"
    validations:
      required: true

  - type: textarea
    id: objectives
    attributes:
      label: "Key Objectives"
      placeholder: "What are the main objectives this goal aims to achieve? What outcomes are we targeting?"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
      placeholder: "Any other relevant information, constraints, or dependencies?"

---
