# Epic Template
name: 2) 🔷 New Epic
description: Create a new epic representing a large body of work that can be broken down into multiple tasks.
title: "🔷[Epic] "
labels: ["epic"]
body:
  - type: markdown
    attributes:
      value: "🔷 New Epic"

  - type: textarea
    id: overview
    attributes:
      label: "Epic Overview"
      placeholder: "What is this epic about? What problem does it solve?"
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: "Scope"
      placeholder: "What is included in this epic? What are the main components or features?"
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: "Dependencies"
      placeholder: "Are there any dependencies on other epics or external factors?"
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: "Status"
      options:
        - "📝 Planning"
        - "🚀 Ready for Development"
        - "⏳ In Progress"
        - "✅ Completed"
    validations:
      required: true

  - type: textarea
    id: related-initiative
    attributes:
      label: "Related Initiative"
      placeholder: "Which strategic initiative does this epic support?"
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "Epic-Level Acceptance Criteria"
      placeholder: "What are the high-level conditions that must be met for this epic to be considered complete?"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options:
        - "🔴 P0 : Critical"
        - "🟠 P1 : High"
        - "🟡 P2 : Medium"
        - "🟢 P3 : Normal"
        - "⚪ P4 : Low"
    validations:
      required: true