# Initiative Template
name: "⭐️ New Initiative"
description: Create a new strategic initiative that encompasses multiple epics.
title: "⭐️ [Initiative] "
body:
  - type: markdown
    attributes:
      value: "🎯 New Strategic Initiative"

  - type: textarea
    id: vision
    attributes:
      label: "Vision Statement"
      placeholder: "What is the overall vision for this initiative? What strategic goal does it serve?"
    validations:
      required: true

  - type: textarea
    id: objectives
    attributes:
      label: "Key Objectives"
      placeholder: "What are the main objectives this initiative aims to achieve? What outcomes are we targeting?"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
      placeholder: "Any other relevant information, constraints, or dependencies?"

---